name : Back Logs 
description : Ajouter un nouveau Back log
title: '[Back log]'
labels : 
  - BackLog 
  - "status : todo"
assignees :
  -NOM_DU_DEV_PAR_DEFAUT
body :
  - type: markdown
    attributes:
      value:  |
        ## Signalement de Backlog — Halyzia
          Remplir tous les champs. 
  - type: input
    id : Utilisateur 
    attributes: 
      label : Nom de l'utilsateur (intern / Beta)
      placeholder : ex. Halissath / Adrien 
    validations:
      required: true
  - type: input
    id : Demande
    attributes: 
       label : Entrez l'intitulé de la Demande
    validations: 
      required : true 
  - type : input 
    id : Description 
    attributes: 
      label: Description
    validations:
      required : true 
  - type: input 
    id: Decision 
    attributes:
      label : Quelle decision a ete prise pour cette demande 
    validations :
      required: true
  - type: input 
    id: Milestone 
    attributes:
      label : Milestone
    validations :
      required: true
  - type : input 
    id : Commentaire 
    attributes:
      label: Commentaire
  





  




