name : Back Logs 
description : Add a new feature request
title: '[Back log]'
labels : 
  - BackLog 
  - "status: todo"
assignees :
  - NOM_DU_DEV_PAR_DEFAUT
body :
  - type: markdown
    attributes:
      value:  |
        **## Backlog Report — Halyzia**
          Please complete all fields.

  - type: input
    id : User 
    attributes: 
      label : User name (internal / beta)
      placeholder : ex. Halissath / Adrien 
    validations:
      required: true
  - type: input
    id : Request
    attributes: 
       label : Enter the request title
    validations: 
      required : true 
  - type : input 
    id : Description 
    attributes: 
      label: Description
    validations:
      required : true 
  - type: input 
    id: Decision 
    attributes:
      label : What decision was made for this request? 
    validations :
      required: true
  - type: input 
    id: Milestone 
    attributes:
      label : Milestone
    validations :
      required: true
  - type: dropdown
    id: assignee_choice
    attributes:
      label: Assigned to
      description: Choisir la personne responsable
      options:
        - Halissath
        - Messaouda
    validations:
      required: true
  - type : input 
    id : Comments
    attributes:
      label: Comments
  





  




