name: Issue Test
description: Signaler une annomalie detecte pendant les tests Halyzia
title: Issue Test
labels:
  - Test
  - 'status: todo'
body:
  - type: markdown
    attributes:
      value: |
        ## Halyzia Issue Report
            Please complete all fields. 
            The issue will be automatically assigned and tracked in the dashboard.
  - type: input
    id: version
    attributes:
      label: Halyzia's version
      placeholder: ex. V1.7.1
    validations:
      required: true
  - type: dropdown
    id: sessiontest
    attributes:
      label: The current test session when the anomaly occurred
      description: |
        See full definitions in PLAN_TEST_AUTO/test-sessions/
      options:
        - '"Rapport de Session : test_messaouda_202-05-05.md"'
        - '"Rapport de Session de Test"'
        - '"Rapport : test_messaouda_2026-05-04.md"'
        - '"Rapport : test_messaouda_2026-05-04_v2.md"'
        - '"Rapport : test_messaouda_2026-05-04_v3.md"'
        - '"Rapport : test_messaouda_2026-05-04_v4.md"'
        - '"Rapport : test_messaouda_2026-05-04_v5.md"'
        - '"Rapport de Session : test_messaouda_2026-05-04_v6.md"'
        - '"Rapport de Session : test_messaouda_2026-05-05.md"'
    validations:
      required: true
  - type: dropdown
    id: format
    attributes:
      label: EEG format
      options:
        - .ncs
        - .edf
        - .TRC
        - .ns5
        - .medd
        - .nsc
        - Autre
    validations:
      required: true
  - type: textarea
    id: test_data
    attributes:
      label: Link to test folder/file
      description: >-
        Link to folder (Drive, server, zip, etc.) or drag and drop your files here

      placeholder: https://...
    validations:
      required: true
  - type: input
    id: pc
    attributes:
      label: Used laptop
      placeholder: ex. MSI / LAPTOP-LQFVND1H / Mac
    validations:
      required: true
  - type: input
    id: testeur
    attributes:
      label: Tester
      placeholder: ex.  Halissath
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severite
      options:
        - Critical - Application crash or data loss
        - Major - Functionality blocked/unavailable
        - Minor - Incorrect behavior but with a workaround available
        - Visual — Display/UI issue only
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Deficiency description
      placeholder: Please describe exactly what happened...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open Halyzia V1.7.1
        2. NEW > Select folder X
        3. Apply a permanent filter...
        4. Observe the bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected results
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual results
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error lines (if any)
      render: shell
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshot
      description: Please place your screanshot here. 
      placeholder: you can add one or multiple screenshots...
    validations:
      required: false
  - type: dropdown
    id: assignee_choice
    attributes:
      label: Assigned to
      description: Select the person responsible for handling this issue.
      options:
        - Halissath
        - Messaouda
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows 10
        - Windows 11
        - macOS
        - other