name: Create Workflow
description: Ajouter un nouveau workflow de test
title: "[WORKFLOW] "
labels : 
  - Fichiers
  

body:
  - type: input
    id: name
    attributes:
      label: Nom du workflow
      placeholder: ex. Workflow 3 — Test export
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: Objectif
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: Checklist
      description: Une ligne = une étape
      placeholder: |
        - [ ] Etape 1
        - [ ] Etape 2
    validations:
      required: true

  - type: input
    id: format
    attributes:
      label: Format fichier
      placeholder: ex. .ncs
    validations:
      required: true

  - type: input
    id: montage
    attributes:
      label: Montage
    validations:
      required: true