name : Issue user
description : Signaler une Issue detecte par des utilisateus 
title : 'Issue Utilisateur'
labels: 
  - Utilisateur
  - status : todo

body: 
  - type : markdown 
    attributes :
      value : |
        ## Signalemnt d'une issue prevenant d'un utilisateur  
        Remplir tous les champs.

  - type: dropdown
    id: Type_du_signalement
    attributes:
      label: Reporting cause
      options:
        - Lack
        - anomaly
        - other
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Halyzia's version 
      placeholder: ex. V1.7.1
    validations:
      required: true
  - type: dropdown
    id: format
    attributes:
      label: EEG file format
      options:
        - .ncs
        - .edf
        - .TRC
        - .ns5
        - .medd
        - .nsc
        - Autre
    validations:
      required: true
  - type: input
    id: fichier
    attributes:
      label: Test file name 
      placeholder: ex. P110_DP002-sieste_micmac-ncs
    validations:
      required: true
  - type: input
    id: pc
    attributes:
      label: Used laptop
      placeholder: ex. MSI / LAPTOP-LQFVND1H / Mac
    validations:
      required: true
  - type: input
    id: testeur
    attributes:
      label: Tester
      placeholder: ex. Halissath 
    validations:
      required: true
  - type: dropdown
    id: severite
    attributes:
      label: Severity
      options:
        - Critical - Application crash or data loss
        - Major - Functionality blocked/unavailable
        - Minor - Incorrect behavior but with a workaround available
        - Visual — Display/UI issue only
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Deficiency description 
      placeholder: Please describe exactly what happened...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open Halyzia V1.7.1
        2. NEW > Select folder X
        3. Apply a permanent filter...
        4. Observe the bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected results
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual results
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error lines (if any)
      render: shell
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshot
      description: Please place your screanshot here. 
      placeholder: you can add one or multiple screenshots...
    validations:
      required: false
  - type: dropdown
    id: assignee_choice
    attributes:
      label: Assigned to
      description: Select the person responsible for handling this issue.
      options:
        - Halissath
        - Messaouda
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows 10
        - Windows 11
        - macOS
        - other