name: Sync Backlog → Test

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |

            const label = context.payload.label.name;
            const issue = context.payload.issue;

            console.log("Label reçu:", label);

            // Si status devient dev
            if (label === "status: dev") {

              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ["Test"]
              });

              console.log("Ajout du label Test");
            }