name: Update Bug Report Dropdown

on:
  workflow_run:
    workflows: ["Create Workflow File"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install js-yaml

      - name: Run script
        run: node .github/Scripts/update_session_test.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .github/ISSUE_TEMPLATE/test_session.yml
          git commit -m "Mise à jour automatique des workflows " || echo "Rien à commit"
          git push https://${{ secrets.GPAT }}@github.com/${{ github.repository }}.git HEAD:main