name: Update Bug Report Dropdown

on:
  push:
    paths:
      - '.github/workflow-definitions/**'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install js-yaml

      - name: Run script
        run: node .github/Scripts/update_bug_report.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .github/ISSUE_TEMPLATE/bug_report.yml
          git commit -m "Mise à jour automatique des workflows" || echo "Rien à commit"
          git push https://${{ secrets.GPAT }}@github.com/${{ github.repository }}.git HEAD:main